package com.orobind.core.entity;

// default package
// Generated 20 Aug, 2014 5:27:25 PM by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;



//import com.eattastic.base.expression.Expression;

import com.orobind.base.utils.StringUtils;

/**
 * PaymentGatewayForm generated by hbm2java
 */
@Entity
@Table(name = "payment_gateway_param", catalog = "orobind")
public class PaymentGatewayParam implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 8392933923400055845L;
    private Integer           id;
    private PaymentGateway    paymentGateway;
    private String            fieldName;
    private String            pgFieldName;
    private String            fieldDesc;
    private String            fieldType;
    private Integer           fieldLength;
    private String            expressionText;
    //private Expression        expression;
    private Boolean           mandatory;
    private Boolean           forDisplay;
    private String            fieldValue;
    private Date created;
	private Date updated;

    public PaymentGatewayParam() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "payment_gateway_id", nullable = false)
    public PaymentGateway getPaymentGateway() {
        return this.paymentGateway;
    }

    public void setPaymentGateway(PaymentGateway paymentGateway) {
        this.paymentGateway = paymentGateway;
    }

    @Column(name = "field_name", length = 48)
    public String getFieldName() {
        return this.fieldName;
    }

    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    @Column(name = "field_desc", length = 256)
    public String getFieldDesc() {
        return this.fieldDesc;
    }

    public void setFieldDesc(String fieldDesc) {
        this.fieldDesc = fieldDesc;
    }

    @Column(name = "field_type", length = 7)
    public String getFieldType() {
        return this.fieldType;
    }

    public void setFieldType(String fieldType) {
        this.fieldType = fieldType;
    }

    @Column(name = "field_length")
    public Integer getFieldLength() {
        return this.fieldLength;
    }

    public void setFieldLength(Integer fieldLength) {
        this.fieldLength = fieldLength;
    }

    @Column(name = "expression_text", length = 256)
    public String getExpressionText() {
        return this.expressionText;
    }

    public void setExpressionText(String expressionText) {
        this.expressionText = expressionText;
    }

    @Column(name = "mandatory")
    public Boolean isMandatory() {
        return this.mandatory;
    }

    public void setMandatory(Boolean mandatory) {
        this.mandatory = mandatory;
    }

    @Column(name = "display")
    public Boolean isForDisplay() {
        return this.forDisplay;
    }

    public void setForDisplay(Boolean display) {
        this.forDisplay = display;
    }

    public void setPgFieldName(String pgFieldName) {
        this.pgFieldName = pgFieldName;
    }

    @Column(name = "pg_field_name")
    public String getPgFieldName() {
        return pgFieldName;
    }

    public void setFieldValue(String fieldValue) {
        this.fieldValue = fieldValue;
    }

    @Transient
    public String getFieldValue() {
        return fieldValue;
    }

    @Column(name = "created")
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "updated")
	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}
    /*@Transient
    public Expression getExpression() {
        return this.expression;
    }
    
    
    public void setExpression(Expression expression) {
        this.expression = expression;
    }*/

    @Override
    public String toString() {
        return "PaymentGatewayParam [fieldName=" + fieldName + ", pgFieldName=" + pgFieldName + ", fieldDesc=" + fieldDesc + ", expressionText=" + expressionText + "]";
    }
}
