package com.orobind.core.entity;

// Generated Mar 30, 2014 10:59:42 AM by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PaymentModeSubtype generated by hbm2java
 */
@Entity
@Table(name = "payment_mode_subtype", catalog = "orobind")
public class PaymentModeSubtype implements java.io.Serializable {

	private static final long serialVersionUID = 6239391486085968703L;

	private Integer id;
	private PaymentMode paymentMode;
	private String code;
	private String displayName;
	private int priority;
	private boolean enabled = false;
	private int minAmount;
	private String allowedGateways;
	private PaymentGateway paymentGateway;
	private PaymentGateway algoPaymentGateway;
	private boolean preferred;
	private String paymentDisplayText;
	private Date created;
	private Date updated;

	public PaymentModeSubtype() {
	}

	public PaymentModeSubtype(PaymentMode paymentMode, String code,
			String displayName, int priority, boolean enabled) {
		this.paymentMode = paymentMode;
		this.code = code;
		this.displayName = displayName;
		this.priority = priority;
		this.enabled = enabled;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_mode_id", nullable = false)
	public PaymentMode getPaymentMode() {
		return this.paymentMode;
	}

	public void setPaymentMode(PaymentMode paymentMode) {
		this.paymentMode = paymentMode;
	}

	@Column(name = "code", nullable = false, length = 48)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "display_name", nullable = false, length = 48)
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@Column(name = "priority", nullable = false)
	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	@Column(name = "enabled", nullable = false)
	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	@Column(name = "min_amount", nullable = false)
	public int getMinAmount() {
		return minAmount;
	}

	public void setMinAmount(int minAmount) {
		this.minAmount = minAmount;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "payment_gateway_id", nullable = false)
	public PaymentGateway getPaymentGateway() {
		return this.paymentGateway;
	}

	public void setPaymentGateway(PaymentGateway paymentGateway) {
		this.paymentGateway = paymentGateway;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "algo_payment_gateway_id", nullable = false)
	public PaymentGateway getAlgoPaymentGateway() {
		return algoPaymentGateway;
	}

	public void setAlgoPaymentGateway(PaymentGateway algoPaymentGateway) {
		this.algoPaymentGateway = algoPaymentGateway;
	}

	@Column(name = "allowed_gateways", length = 200)
	public String getAllowedGateways() {
		return this.allowedGateways;
	}

	public void setAllowedGateways(String allowedGateways) {
		this.allowedGateways = allowedGateways;
	}

	@Override
	public String toString() {
		StringBuilder str = new StringBuilder();
		str.append("[id: " + id);
		str.append(", code: " + code);
		str.append(", displayname: " + displayName);
		str.append(", priority: " + priority);
		str.append(", enaled: " + enabled);
		str.append(", minAmount: " + minAmount);
		str.append(", algoPaymentGateway: " + algoPaymentGateway);
		str.append(", paymentGateway: " + paymentGateway + "]");
		return str.toString();
	}

	@Column(name = "preferred", nullable = false)
	public boolean isPreferred() {
		return preferred;
	}

	public void setPreferred(boolean preferred) {
		this.preferred = preferred;
	}

	@Column(name = "payment_display_text")
	public String getPaymentDisplayText() {
		return paymentDisplayText;
	}

	public void setPaymentDisplayText(String paymentDisplayText) {
		this.paymentDisplayText = paymentDisplayText;
	}
	
	@Column(name = "created")
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "updated")
	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

}
