package com.orobind.core.entity;

// default package
// Generated 20 Aug, 2014 5:27:25 PM by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

/**
 * PaymentGateway generated by hbm2java
 */
@Entity
@Table(name = "payment_gateway", catalog = "orobind")
public class PaymentGateway implements java.io.Serializable {

	/**
     * 
     */
	private static final long serialVersionUID = 6203776934692177148L;
	private Integer id;
	private String name;
	private String className;
	private String identificationCode;
	private String secretKey;
	private String redirectUrl;
	private String returnUrl;
	private String mode;
	private Boolean enabled;
	private Boolean isDefault;
	private Set<PaymentGatewayParam> paymentGatewayParams = new HashSet<PaymentGatewayParam>(
			0);
	private String reconciliationDateExp;
	private Date created;
	private Date updated;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "class_name", nullable = true)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Column(name = "identification_code", length = 256)
	public String getIdentificationCode() {
		return this.identificationCode;
	}

	public void setIdentificationCode(String identificationCode) {
		this.identificationCode = identificationCode;
	}

	@Column(name = "secret_key", length = 256)
	public String getSecretKey() {
		return this.secretKey;
	}

	public void setSecretKey(String secretKey) {
		this.secretKey = secretKey;
	}

	@Column(name = "redirect_url", length = 256)
	public String getRedirectUrl() {
		return this.redirectUrl;
	}

	public void setRedirectUrl(String redirectUrl) {
		this.redirectUrl = redirectUrl;
	}

	@Column(name = "return_url", length = 256)
	public String getReturnUrl() {
		return this.returnUrl;
	}

	public void setReturnUrl(String returnUrl) {
		this.returnUrl = returnUrl;
	}

	@Column(name = "mode", length = 5)
	public String getMode() {
		return this.mode;
	}

	public void setMode(String mode) {
		this.mode = mode;
	}

	@Column(name = "enabled")
	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	@Column(name = "default")
	public Boolean isDefault() {
		return this.isDefault;
	}

	public void setDefault(Boolean isDefault) {
		this.isDefault = isDefault;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "paymentGateway")
	@OrderBy("id")
	public Set<PaymentGatewayParam> getPaymentGatewayParams() {
		return this.paymentGatewayParams;
	}

	public void setPaymentGatewayParams(
			Set<PaymentGatewayParam> paymentGatewayParams) {
		this.paymentGatewayParams = paymentGatewayParams;
	}

	@Column(name = "reconciliation_date_exp")
	public String getReconciliationDateExp() {
		return reconciliationDateExp;
	}

	public void setReconciliationDateExp(String reconciliationDateExp) {
		this.reconciliationDateExp = reconciliationDateExp;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PaymentGateway other = (PaymentGateway) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("PaymentGateway [");
		if (id != null) {
			builder.append("id=");
			builder.append(id);
			builder.append(", ");
		}
		if (name != null) {
			builder.append("name=");
			builder.append(name);
			builder.append(", ");
		}
		if (className != null) {
			builder.append("className=");
			builder.append(className);
			builder.append(", ");
		}
		if (identificationCode != null) {
			builder.append("identificationCode=");
			builder.append(identificationCode);
		}
		builder.append("]");
		return builder.toString();
	}

	@Column(name = "created")
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "updated")
	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}
}
